// <reference types="cypress" />

const adminRxHost = /https?:\/\/(localhost|127.0.0.1):8000/;
const adminRxLogin = new RegExp(`${adminRxHost.source}\/api\/login(.*)?`);
const adminRxMe = new RegExp(`${adminRxHost.source}\/api\/me(.*)?`);
const rxAdminStats = new RegExp(`${adminRxHost.source}\/api\/admin\/pets\/dashboard\/stats(.*)?`);
const rxAdminActivity = new RegExp(`${adminRxHost.source}\/api\/admin\/pets\/dashboard\/activity(.*)?`);
const rxAdminPets = new RegExp(`${adminRxHost.source}\/api\/admin\/pets(.*)?`);

describe('Admin Workflow', () => {
  beforeEach(() => {
    cy.clearLocalStorage()
    // Ignore hydration errors caused by the <style> tag in AdminDashboard
    Cypress.on('uncaught:exception', (err) => {
      if (err.message.includes('Hydration failed') || err.message.includes('server rendered HTML')) {
        return false
      }
    })
  })

  it('logs in as admin and redirects to dashboard', () => {
    cy.intercept('POST', adminRxLogin, {
      statusCode: 200,
      body: { token: 'fake-token', user: { id: 1, name: 'Admin User', role: 'admin' } },
    }).as('adminLogin')

    cy.intercept('GET', adminRxMe, {
      statusCode: 200,
      body: { user: { id: 1, name: 'Admin User', role: 'admin' } },
    }).as('adminMe')

    cy.visit('/login')
    cy.get('[data-cy=login-email]').type('admin@example.com', { force: true })
    cy.get('[data-cy=login-password]').type('AdminPass123', { force: true })
    cy.get('[data-cy=login-submit]').click()

    cy.wait(['@adminLogin', '@adminMe'])
    cy.url().should('include', '/admin/dashboard')
  })

  it('displays admin dashboard with stats and activity', () => {
    cy.intercept('POST', adminRxLogin, {
      statusCode: 200,
      body: { token: 'fake-token', user: { id: 1, name: 'Admin User', role: 'admin' } },
    }).as('adminLogin')

    cy.intercept('GET', adminRxMe, {
      statusCode: 200,
      body: { user: { id: 1, name: 'Admin User', role: 'admin' } },
    }).as('adminMe')

    cy.intercept('GET', rxAdminStats, {
      statusCode: 200,
      body: { total: 25, available: 15, adopted: 8, pending: 2, by_species: [], by_gender: [] }
    }).as('adminStats')

    cy.intercept('GET', rxAdminActivity, {
      statusCode: 200,
      body: { recent_additions: [], recent_adoptions: [] }
    }).as('adminActivity')

    cy.visit('/login')
    cy.get('[data-cy=login-email]').type('admin@example.com', { force: true })
    cy.get('[data-cy=login-password]').type('AdminPass123', { force: true })
    cy.get('[data-cy=login-submit]').click()
    
    cy.wait(['@adminLogin', '@adminMe'])
    
    // Ensure the loading screen is gone before checking the dashboard
    cy.contains('Loading your dashboard...').should('not.exist')
    cy.wait(['@adminStats', '@adminActivity'])

    // Verify dashboard loads
    cy.get('[data-cy=admin-dashboard]', { timeout: 15000 }).should('be.visible')
    cy.contains('h1', 'Dashboard').should('be.visible')

    // FIX: Match the actual data-cy generated by StatCard ('stat-total-pets')
    cy.get('[data-cy=stat-total-pets]').should('contain', '25')
    cy.get('[data-cy=stat-available]').should('contain', '15')

    // FIX: Component uses "Recent Additions" not "Recent Activity"
    cy.contains('Recent Additions').should('exist')
  })

  it('navigates to admin pets page and displays pet list', () => {
    cy.intercept('POST', adminRxLogin, {
      statusCode: 200,
      body: { token: 'fake-token', user: { id: 1, role: 'admin' } },
    }).as('adminLogin')

    cy.intercept('GET', adminRxMe, {
      statusCode: 200,
      body: { user: { id: 1, role: 'admin' } },
    }).as('adminMe')

    cy.intercept('GET', rxAdminPets, {
      statusCode: 200,
      body: [{ id: 1, name: 'Buddy', species: 'dog', status: 'available' }]
    }).as('adminPets')

    cy.visit('/login')
    cy.get('[data-cy=login-email]').type('admin@example.com', { force: true })
    cy.get('[data-cy=login-password]').type('AdminPass123', { force: true })
    cy.get('[data-cy=login-submit]').click()
    cy.wait(['@adminLogin', '@adminMe'])

    cy.visit('/admin/pets')
    cy.wait('@adminPets')
    cy.contains('Buddy').should('be.visible')
  })

  it('adds a new pet via modal with image upload', () => {
    cy.intercept('POST', adminRxLogin, {
      statusCode: 200,
      body: { token: 'fake-token', user: { id: 1, role: 'admin' } },
    }).as('adminLogin')

    cy.intercept('GET', adminRxMe, {
      statusCode: 200,
      body: { user: { id: 1, role: 'admin' } },
    }).as('adminMe')

    cy.intercept('GET', rxAdminPets, { statusCode: 200, body: [] }).as('adminPets')

    cy.visit('/login')
    cy.get('[data-cy=login-email]').type('admin@example.com', { force: true })
    cy.get('[data-cy=login-password]').type('AdminPass123', { force: true })
    cy.get('[data-cy=login-submit]').click()
    cy.wait(['@adminLogin', '@adminMe'])

    cy.visit('/admin/pets')
    cy.wait('@adminPets')

    cy.get('[data-cy=add-pet-button]').click()

    cy.intercept('POST', rxAdminPets, { 
      statusCode: 200, 
      body: { id: 3, name: 'Max', species: 'dog', status: 'available' } 
    }).as('createPet')

    cy.intercept('GET', rxAdminPets, { 
      statusCode: 200, 
      body: [{ id: 3, name: 'Max', species: 'dog', status: 'available' }] 
    }).as('adminPetsUpdated')

    cy.get('[data-cy=pet-name]').type('Max')
    cy.get('[data-cy=pet-species]').type('dog')
    cy.get('[data-cy=pet-type]').type('Golden Retriever')
    cy.get('[data-cy=pet-age]').type('3')
    cy.get('[data-cy=pet-gender]').select('male')
    cy.get('[data-cy=pet-status]').select('available')
    cy.get('[data-cy=pet-description]').type('Very friendly dog')

    // FIX: Generate dummy file instead of using cy.fixture()
    cy.get('[data-cy=pet-image-upload]').selectFile({
      contents: Cypress.Buffer.from('dummy image data'),
      fileName: 'pet.jpg',
      mimeType: 'image/jpeg'
    }, { force: true })

    cy.get('[data-cy=create-pet-submit]').click()
    cy.wait(['@createPet', '@adminPetsUpdated'])

    cy.contains('Max').should('be.visible')
  })
})