// <reference types="cypress" />

const adminRxHost = /https?:\/\/(localhost|127.0.0.1):8000/;
const adminRxLogin = new RegExp(`${adminRxHost.source}\/api\/login(.*)?`);
const adminRxMe = new RegExp(`${adminRxHost.source}\/api\/me(.*)?`);
const rxAdminStats = new RegExp(`${adminRxHost.source}\/api\/admin\/pets\/dashboard\/stats(.*)?`);
const rxAdminActivity = new RegExp(`${adminRxHost.source}\/api\/admin\/pets\/dashboard\/activity(.*)?`);
const rxAdminPets = new RegExp(`${adminRxHost.source}\/api\/admin\/pets(.*)?`);
const rxAdminRequests = new RegExp(`${adminRxHost.source}\/api\/admin\/adoption-applications(.*)?`);
const rxAdminUpdateStatus = new RegExp(`${adminRxHost.source}\/api\/admin\/adoption-applications\/\\d+\/status(.*)?`);

describe('Admin Workflow', () => {
  beforeEach(() => {
    cy.clearLocalStorage()
    Cypress.on('uncaught:exception', (err) => {
      if (err.message.includes('Hydration failed') || err.message.includes('server rendered HTML')) {
        return false
      }
    })
  })

  it('logs in as admin and redirects to dashboard', () => {
    cy.intercept('POST', adminRxLogin, {
      statusCode: 200,
      body: { token: 'fake-token', user: { id: 1, name: 'Admin User', role: 'admin' } },
    }).as('adminLogin')

    cy.intercept('GET', adminRxMe, {
      statusCode: 200,
      body: { user: { id: 1, name: 'Admin User', role: 'admin' } },
    }).as('adminMe')

    cy.visit('/login')
    cy.get('[data-cy=login-email]').type('admin@example.com', { force: true })
    cy.get('[data-cy=login-password]').type('AdminPass123', { force: true })
    cy.get('[data-cy=login-submit]').click()

    cy.wait(['@adminLogin', '@adminMe'])
    cy.url().should('include', '/admin/dashboard')
  })

  it('displays admin dashboard with stats and activity', () => {
    cy.intercept('POST', adminRxLogin, {
      statusCode: 200,
      body: { token: 'fake-token', user: { id: 1, name: 'Admin User', role: 'admin' } },
    }).as('adminLogin')

    cy.intercept('GET', adminRxMe, {
      statusCode: 200,
      body: { user: { id: 1, name: 'Admin User', role: 'admin' } },
    }).as('adminMe')

    cy.intercept('GET', rxAdminStats, {
      statusCode: 200,
      body: { total: 25, available: 15, adopted: 8, pending: 2, by_species: [], by_gender: [] }
    }).as('adminStats')

    cy.intercept('GET', rxAdminActivity, {
      statusCode: 200,
      body: { recent_additions: [], recent_adoptions: [] }
    }).as('adminActivity')

    cy.visit('/login')
    cy.get('[data-cy=login-email]').type('admin@example.com', { force: true })
    cy.get('[data-cy=login-password]').type('AdminPass123', { force: true })
    cy.get('[data-cy=login-submit]').click()
    
    cy.wait(['@adminLogin', '@adminMe'])
    
    // Ensure the loading screen is gone before checking the dashboard
    cy.contains('Loading your dashboard...').should('not.exist')
    cy.wait(['@adminStats', '@adminActivity'])

    // Verify dashboard loads
    cy.get('[data-cy=admin-dashboard]', { timeout: 15000 }).should('be.visible')
    cy.contains('h1', 'Dashboard').should('be.visible')

    // FIX: Match the actual data-cy generated by StatCard ('stat-total-pets')
    cy.get('[data-cy=stat-total-pets]').should('contain', '25')
    cy.get('[data-cy=stat-available]').should('contain', '15')

    // FIX: Component uses "Recent Additions" not "Recent Activity"
    cy.contains('Recent Additions').should('exist')
  })

  it('navigates to admin pets page and displays pet list', () => {
    cy.intercept('POST', adminRxLogin, {
      statusCode: 200,
      body: { token: 'fake-token', user: { id: 1, role: 'admin' } },
    }).as('adminLogin')

    cy.intercept('GET', adminRxMe, {
      statusCode: 200,
      body: { user: { id: 1, role: 'admin' } },
    }).as('adminMe')

    cy.intercept('GET', rxAdminPets, {
      statusCode: 200,
      body: [{ id: 1, name: 'Buddy', species: 'dog', status: 'available' }]
    }).as('adminPets')

    cy.visit('/login')
    cy.get('[data-cy=login-email]').type('admin@example.com', { force: true })
    cy.get('[data-cy=login-password]').type('AdminPass123', { force: true })
    cy.get('[data-cy=login-submit]').click()
    cy.wait(['@adminLogin', '@adminMe'])

    cy.visit('/admin/pets')
    cy.wait('@adminPets')
    cy.contains('Buddy').should('be.visible')
  })

  it('navigates to admin requests page and displays adoption applications', () => {
    cy.intercept('POST', adminRxLogin, { statusCode: 200, body: { token: 'f', user: { id: 1, role: 'admin' } } }).as('adminLogin')
    cy.intercept('GET', adminRxMe, { statusCode: 200, body: { user: { id: 1, role: 'admin' } } }).as('adminMe')
    
    cy.intercept('GET', rxAdminRequests, {
      statusCode: 200,
      body: [
        { id: 1, user_id: 2, pet_id: 1, status: 'pending', created_at: new Date().toISOString(), user: { name: 'John Doe' }, pet: { name: 'Buddy', species: 'dog' } },
        { id: 2, user_id: 3, pet_id: 2, status: 'approved', created_at: new Date().toISOString(), user: { name: 'Jane Smith' }, pet: { name: 'Whiskers', species: 'cat' } }
      ]
    }).as('adminRequests')

    cy.visit('/login')
    cy.get('[data-cy=login-email]').type('admin@example.com', { force: true })
    cy.get('[data-cy=login-password]').type('AdminPass123', { force: true })
    cy.get('[data-cy=login-submit]').click()
    cy.wait(['@adminLogin', '@adminMe'])

    cy.visit('/admin/requests')
    cy.wait('@adminRequests')
    
    cy.get('[data-cy=admin-requests-header]').should('be.visible')
    cy.get('[data-cy=admin-request-row-1]').should('contain', 'Buddy')
    
    // Test filter
    cy.get('[data-cy=admin-requests-search]').type('Whiskers')
    cy.get('[data-cy=admin-request-row-2]').should('be.visible')
    cy.get('[data-cy=admin-request-row-1]').should('not.exist')
  })

  it('approves an adoption request and verifies status updates', () => {
    cy.intercept('POST', adminRxLogin, { statusCode: 200, body: { token: 'f', user: { id: 1, role: 'admin' } } }).as('adminLogin')
    cy.intercept('GET', adminRxMe, { statusCode: 200, body: { user: { id: 1, role: 'admin' } } }).as('adminMe')
    
    cy.intercept('GET', rxAdminRequests, {
      statusCode: 200,
      body: [{ id: 1, user_id: 2, pet_id: 1, status: 'pending', created_at: new Date().toISOString(), user: { name: 'John Doe' }, pet: { name: 'Buddy' } }]
    }).as('adminRequests')

    // Mock the PUT request - MUST return a body to avoid JSON parsing errors
    cy.intercept('PUT', rxAdminUpdateStatus, {
      statusCode: 200,
      body: { message: 'Status updated' }
    }).as('updateStatus')

    cy.visit('/login')
    cy.get('[data-cy=login-email]').type('admin@example.com', { force: true })
    cy.get('[data-cy=login-password]').type('AdminPass123', { force: true })
    cy.get('[data-cy=login-submit]').click()
    cy.wait(['@adminLogin', '@adminMe'])

    cy.visit('/admin/requests')
    cy.wait('@adminRequests')

    // Open options and details
    cy.get('[data-cy=admin-request-row-1]').find('button').contains('⋮').click()
    cy.contains('View Details').click()

    // Perform Approval
    cy.get('[data-cy=admin-approve-application-btn]').click()
    cy.get('[data-cy=admin-action-confirm-btn-approve]').click()

    // Wait for the API call to complete
    cy.wait('@updateStatus')

    // Verify UI updates (component updates state manually, so we don't wait for a GET refresh)
    cy.contains('Application approved successfully!').should('be.visible')
    cy.get('[data-cy=admin-request-row-1]').should('contain', 'Approved')
  })

  it('denies an adoption request and verifies status updates', () => {
    cy.intercept('POST', adminRxLogin, { statusCode: 200, body: { token: 'f', user: { id: 1, role: 'admin' } } }).as('adminLogin')
    cy.intercept('GET', adminRxMe, { statusCode: 200, body: { user: { id: 1, role: 'admin' } } }).as('adminMe')
    
    cy.intercept('GET', rxAdminRequests, {
      statusCode: 200,
      body: [{ id: 1, user_id: 2, pet_id: 1, status: 'pending', created_at: new Date().toISOString(), user: { name: 'John Doe' }, pet: { name: 'Buddy' } }]
    }).as('adminRequests')

    // FIX: Provide a body {} to satisfy the frontend's .json() call
    cy.intercept('PUT', rxAdminUpdateStatus, {
      statusCode: 200,
      body: { message: 'Denied' } 
    }).as('updateStatus')

    cy.visit('/login')
    cy.get('[data-cy=login-email]').type('admin@example.com', { force: true })
    cy.get('[data-cy=login-password]').type('AdminPass123', { force: true })
    cy.get('[data-cy=login-submit]').click()
    cy.wait(['@adminLogin', '@adminMe'])

    cy.visit('/admin/requests')
    cy.wait('@adminRequests')

    cy.get('[data-cy=admin-request-row-1]').find('button').contains('⋮').click()
    cy.contains('View Details').click()

    // Perform Denial
    cy.get('[data-cy=admin-deny-application-btn]').click()
    cy.get('[data-cy=admin-action-confirm-btn-deny]').click()

    cy.wait('@updateStatus')

    // Verify UI updates
    cy.contains('Application denied successfully!').should('be.visible')
    cy.get('[data-cy=admin-request-row-1]').should('contain', 'Denied')
  })
})
