server {
    listen 80;
    server_name _;
    server_tokens off;

    # Gzip Compression
    gzip on;
    gzip_vary on;
    gzip_min_length 1000;
    gzip_proxied any;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    # Security Headers
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Content-Type-Options "nosniff";
    add_header Referrer-Policy "strict-origin-when-cross-origin";
    root /var/www/html/public;
    client_max_body_size 10M;
    index index.php;
    # Serve static files from storage
    location /storage {
        alias /var/www/html/storage/app/public;
        try_files $uri =404;
        expires max;
        access_log off;
        add_header Cache-Control "public, immutable";
    }
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # location /api {
    #     try_files $uri $uri/ /index.php?$query_string;
    # }

    location ~ \.php$ {
        fastcgi_pass backend:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }
}